"""add crawl_jobs completed_reason column

Revision ID: 4a98f5105755
Revises: 060a6d6daaed
Create Date: 2026-04-02 04:16:14.644182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a98f5105755'
down_revision: Union[str, None] = '060a6d6daaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_column('completed_reason')

    # ### end Alembic commands ###
